pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t java-memory-test:latest .'
            }
        }

        stage('Deploying to Kubernetes test') {
            steps {
                sh 'kubectl apply -f java-memory-test-deployment.yaml'
            }
        }

        stage('Verify Pod status') {
            steps {
                sh 'kubectl get pods'
            }
        }
    }
}