pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Java Application t2') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Java Docker Image') {
            steps {
                sh 'docker build -t java-memory-test:latest .'
            }
        }

        stage('Deploy OOM Test to Kubernetes') {
            steps {
                sh 'kubectl apply -f java-memory-test-oom-deployment.yaml'
            }
        }

        stage('Verify Pods') {
            steps {
                sh 'kubectl get pods -l app=java-memory-test-oom'
            }
        }
    }
}